import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { SITE_ORIGIN } from "../src/site/constants.js";
import {
  locales,
  projectRegistry,
  projectSlugs,
  siteContent
} from "../src/content/site.js";

const BRAND_IMAGE_SRC = "/assets/NeoCom_Icon_Final_v2.svg";
const PAGE_ENTRY_SRC = "/src/page-entry.tsx";
const WATCH_ROOTS = ["src/content", "src/site", "scripts/static-site.mjs"];

function getLandingPath(locale) {
  return locale === "pt-br" ? "/pt-br/" : "/en/";
}

function getProjectPath(locale, projectSlug) {
  return `${getLandingPath(locale)}projects/${projectSlug}/`;
}

function getPagePath(page) {
  if (page.pageKind === "project") {
    return getProjectPath(page.locale, page.projectSlug);
  }

  return getLandingPath(page.locale);
}

function getPageFilePath(page) {
  if (page.pageKind === "project") {
    return `${page.locale}/projects/${page.projectSlug}/index.html`;
  }

  return `${page.locale}/index.html`;
}

function getInputKey(page) {
  if (page.pageKind === "landing") {
    return page.locale === "pt-br" ? "ptBrLanding" : "enLanding";
  }

  const localeKey = page.locale === "pt-br" ? "ptBr" : "en";

  return `${localeKey}${toPascalCase(page.projectSlug)}`;
}

function getAbsoluteUrl(pathname) {
  return new URL(pathname, `${SITE_ORIGIN}/`).toString();
}

function toPascalCase(value) {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&#39;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function getHrefLang(locale) {
  return locale === "pt-br" ? "pt-BR" : "en";
}

function renderAlternateLinks(page) {
  const alternateLines = [
    '    <link rel="alternate" hreflang="x-default" href="https://neocom.cloud/" />'
  ];

  for (const locale of locales) {
    const href = getAbsoluteUrl(
      page.pageKind === "project"
        ? getProjectPath(locale, page.projectSlug)
        : getLandingPath(locale)
    );

    alternateLines.push(
      `    <link rel="alternate" hreflang="${getHrefLang(locale)}" href="${href}" />`
    );
  }

  return alternateLines.join("\n");
}

function getPageSeo(page) {
  const copy = siteContent[page.locale];

  if (page.pageKind === "landing") {
    return {
      title: copy.seo.landing.title,
      description: copy.seo.landing.description,
      ogDescription: copy.seo.landing.ogDescription,
      twitterDescription: copy.seo.landing.twitterDescription,
      imageSrc: BRAND_IMAGE_SRC,
      ogType: "website"
    };
  }

  const project = copy.projects.items[page.projectSlug];
  const seo = copy.seo.projects[page.projectSlug];
  const registryEntry = projectRegistry[page.projectSlug];

  return {
    title: `${project.name} | NeoCom`,
    description: seo.description,
    ogDescription: seo.ogDescription,
    twitterDescription: seo.twitterDescription,
    imageSrc: registryEntry.socialImageSrc ?? registryEntry.artSrc,
    ogType: "article"
  };
}

export function getStaticPageDefinitions() {
  const pages = [];

  for (const locale of locales) {
    pages.push({
      locale,
      pageKind: "landing"
    });

    for (const projectSlug of projectSlugs) {
      pages.push({
        locale,
        pageKind: "project",
        projectSlug
      });
    }
  }

  return pages;
}

export function getViteInputMap(rootDir) {
  const inputs = {
    root: resolve(rootDir, "index.html"),
    notFound: resolve(rootDir, "404.html")
  };

  for (const page of getStaticPageDefinitions()) {
    inputs[getInputKey(page)] = resolve(rootDir, getPageFilePath(page));
  }

  return inputs;
}

export function renderStaticPage(page) {
  const copy = siteContent[page.locale];
  const path = getPagePath(page);
  const seo = getPageSeo(page);
  const attributes = [
    `lang="${escapeHtml(copy.htmlLang)}"`,
    `data-locale="${escapeHtml(page.locale)}"`,
    `data-page-kind="${escapeHtml(page.pageKind)}"`,
    'data-theme="light"'
  ];

  if (page.pageKind === "project") {
    if (projectRegistry[page.projectSlug].template !== "standard") {
      throw new Error(`Unsupported project template: ${page.projectSlug}`);
    }

    attributes.splice(
      3,
      0,
      `data-project-slug="${escapeHtml(page.projectSlug)}"`
    );
  }

  return `<!doctype html>
<!-- Generated by scripts/generate-pages.mjs -->
<html ${attributes.join(" ")}>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(seo.title)}</title>
    <meta
      name="description"
      content="${escapeHtml(seo.description)}"
    />
    <link rel="canonical" href="${getAbsoluteUrl(path)}" />
${renderAlternateLinks(page)}
    <meta property="og:type" content="${seo.ogType}" />
    <meta property="og:site_name" content="NeoCom" />
    <meta property="og:locale" content="${escapeHtml(copy.ogLocale)}" />
    <meta property="og:title" content="${escapeHtml(seo.title)}" />
    <meta
      property="og:description"
      content="${escapeHtml(seo.ogDescription)}"
    />
    <meta property="og:url" content="${getAbsoluteUrl(path)}" />
    <meta property="og:image" content="${getAbsoluteUrl(seo.imageSrc)}" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="${escapeHtml(seo.title)}" />
    <meta
      name="twitter:description"
      content="${escapeHtml(seo.twitterDescription)}"
    />
    <meta name="twitter:image" content="${getAbsoluteUrl(seo.imageSrc)}" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="manifest" href="/site.webmanifest" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${PAGE_ENTRY_SRC}"></script>
  </body>
</html>
`;
}

export function renderSitemapXml() {
  const urls = [
    "https://neocom.cloud/",
    ...getStaticPageDefinitions().map((page) => getAbsoluteUrl(getPagePath(page)))
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((url) => `  <url>\n    <loc>${url}</loc>\n  </url>`).join("\n")}
</urlset>
`;
}

async function writeGeneratedFile(rootDir, relativePath, contents) {
  const filePath = resolve(rootDir, relativePath);

  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, contents, "utf8");
}

export async function generateStaticFiles(rootDir) {
  for (const page of getStaticPageDefinitions()) {
    await writeGeneratedFile(rootDir, getPageFilePath(page), renderStaticPage(page));
  }

  await writeGeneratedFile(rootDir, "public/sitemap.xml", renderSitemapXml());
}

function isWatchedStaticSource(rootDir, changedFile) {
  const absoluteFile = resolve(changedFile);

  return WATCH_ROOTS.some((relativePath) =>
    absoluteFile.startsWith(resolve(rootDir, relativePath))
  );
}

export function createStaticPagesPlugin(rootDir) {
  return {
    name: "neocom-static-pages",
    apply: "serve",
    configureServer(server) {
      server.watcher.add(WATCH_ROOTS.map((relativePath) => resolve(rootDir, relativePath)));

      const handleChange = async (file) => {
        if (!isWatchedStaticSource(rootDir, file)) {
          return;
        }

        await generateStaticFiles(rootDir);
        server.ws.send({ type: "full-reload" });
      };

      server.watcher.on("change", handleChange);

      return () => {
        server.watcher.off("change", handleChange);
      };
    }
  };
}
